version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "type: dependencies"
      - "javascript"
    ignore:
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node-fetch"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      day: "friday"
      interval: "monthly"
    target-branch: "v4.x"
    labels:
      - "type: dependencies"
      - "javascript"
    ignore:
      - dependency-name: "bootstrap"
        update-types: ["version-update:semver-major"]
      - dependency-name: "node-fetch"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "java"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      day: "friday"
      interval: "monthly"
    target-branch: "v4.x"
    labels:
      - "type: dependencies"
      - "java"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "github_actions"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      day: "friday"
      interval: "monthly"
    target-branch: "v4.x"
    labels:
      - "type: dependencies"
      - "github_actions"
