version: '3.9'
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-urlaubsverwaltung}
      POSTGRES_USER: ${POSTGRES_USER:-urlaubsverwaltung}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-urlaubsverwaltung}
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "$$POSTGRES_DB" ]
      interval: 3s
      timeout: 1s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'

  keycloak:
    build: keycloak/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8090
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_HEALTH_ENABLED: 'true'
    ports:
      - '8090:8090'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/auth/health/ready"]
      interval: 30s
      timeout: 30s
      retries: 5

volumes:
  db:
    driver: local
