version: '3.9'
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-urlaubsverwaltung}
      POSTGRES_USER: ${POSTGRES_USER:-urlaubsverwaltung}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-urlaubsverwaltung}
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 3s
      timeout: 1s
      retries: 5

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'

  app:
    image: urlaubsverwaltung/urlaubsverwaltung:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: 'demodata'
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgresql/urlaubsverwaltung'
      SPRING_DATASOURCE_USERNAME: 'urlaubsverwaltung'
      SPRING_DATASOURCE_PASSWORD: 'urlaubsverwaltung'
      SPRING_MAIL_HOST: 'mailhog'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  db:
    driver: local
